name: Update Open Source Events Calendar

on:
  schedule:
    - cron: "0 0 * * *" # Run once daily at midnight UTC
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Run calendar generator
        run: node scripts/generate_ics.js

      - name: Commit and push if changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add events.json events.ics
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update calendar files" && git push https://x-access-token:${GH_PAT}@github.com/jonamarkin/ose-calendar.git main)
